### PR TITLE
feat: manage kibana roles

### PR DESCRIPTION
**Pull request by jfroche**
implements api operations on role:
 - add/update
 - delete
 - get

based on https://www.elastic.co/guide/en/kibana/current/role-management-api.html

We have to enable xpack security in elasticsearch and kibana

### CODE REVIEW

**Comment by jfroche** [comment]
This pull request depends on #30

**Comment by ewilde** [comment]
@jfroche thanks for this contribution I merged #30 and this PR now needs conflicts resolving. If you are able to do that, that would be awesome. Thanks :pray:

**Comment by jfroche** [comment]
rebased.
We still have this logzio job failing: https://travis-ci.org/ewilde/go-kibana/jobs/580892255
any idea why ? login/password change ?

<blockquote><div><strong><a href="https://travis-ci.org/ewilde/go-kibana/jobs/580892255">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by devenney** [comment]
Hey @jfroche, the build fails because Travis protects the encrypted variables. It's effectively to prevent people just echoing them with a pull request.

I can create a branch from yours to force a valid test run but I'm not sure that's sustainable. Do you have any thoughts @ewilde?

**Review by ewilde — APPROVED** [review]
LGTM 💪 sorry it took so long for a review

**Pull request merged**
